<a href="https://colab.research.google.com/github/JohnYechanJo/AI-Study/blob/main/colab/Week8_3_Deep_Learning_Frameworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
data = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
data

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
data[:, 1].assign(0)
data

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 0., 3.],
       [4., 0., 6.]], dtype=float32)>

In [4]:
data @ tf.transpose(data)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 22.],
       [22., 52.]], dtype=float32)>

In [5]:
data * data

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0.,  9.],
       [16.,  0., 36.]], dtype=float32)>

In [6]:
import torch

In [7]:
data = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
data

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
data[:, 1] = 0
data

tensor([[1., 0., 3.],
        [4., 0., 6.]])

In [9]:
data @ data.T

tensor([[10., 22.],
        [22., 52.]])

In [10]:
data * data

tensor([[ 1.,  0.,  9.],
        [16.,  0., 36.]])